version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 500
      runas: ubuntu

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ubuntu